import type { NextPage } from "next";
import Head from "next/head";

import Link from "next/link";
import channels from "../data/channels.json";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container max-w-screen-md mx-auto my-10">
        <div className="mx-2">
          <h1 className="text-5xl font-bold text-center mb-4">チャンネル</h1>
          <ul>
            {channels.map((channel) => (
              <li key={channel.id}>
                <Link href={`channel/${channel.id}`}>
                  <a className="border block my-2 p-10 rounded-3xl text-xl hover:bg-gray-100">
                    {channel.name}
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  );
};

export default Home;
